In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

train=r"C:\Users\nehaa\Desktop\int\task2\archive (2)\fraudTrain.csv"
test=r"C:\Users\nehaa\Desktop\int\task2\archive (2)\fraudTest.csv"

d1=pd.read_csv(train).sample(n=50000,random_state=42)
d2=pd.read_csv(test).sample(n=20000,random_state=42)
d=pd.concat([d1,d2],ignore_index=True)

d=d.drop(columns=['trans_num','first','last','dob','street','city','state','zip','merchant','job'])

e=LabelEncoder()
d['category']=e.fit_transform(d['category'])
d['gender']=e.fit_transform(d['gender'])

d['trans_date_trans_time']=pd.to_datetime(d['trans_date_trans_time'])
d['hour']=d['trans_date_trans_time'].dt.hour
d['day']=d['trans_date_trans_time'].dt.day
d['month']=d['trans_date_trans_time'].dt.month
d=d.drop(columns=['trans_date_trans_time'])

x=d.drop(columns=['is_fraud'])
y=d['is_fraud']

s=StandardScaler()
x=s.fit_transform(x)

x1,x2,y1,y2=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

m={"Logistic Regression":LogisticRegression(),
   "RandomForest1":RandomForestClassifier(n_estimators=50,max_depth=10,n_jobs=-1,warm_start=True),
   "RandomForest2":RandomForestClassifier(n_estimators=100,max_depth=15,n_jobs=-1,warm_start=True)}

for n,v in m.items():
    v.fit(x1,y1)
    yp=v.predict(x2)
    yp1=v.predict_proba(x2)[:,1]

    r=pd.DataFrame({'Actual':y2.values,'Prob':yp1})
    r['Actual']=r['Actual'].map({0:'Legit',1:'Fraud'})

    f=r.sample(10,random_state=42)

    print("\n",n,"Model")
    print("Acc:",accuracy_score(y2,yp))
    print("Matrix:\n",confusion_matrix(y2,yp))
    print("\n Cases:")
    print(f)


 Logistic Regression Model
Acc: 0.9938571428571429
Matrix:
 [[13914    12]
 [   74     0]]

 Cases:
      Actual      Prob
2900   Legit  0.003211
3143   Legit  0.003326
8231   Legit  0.003552
3855   Legit  0.005271
8045   Legit  0.004124
7653   Legit  0.003730
8610   Legit  0.002261
7310   Legit  0.005164
10175  Legit  0.005032
5538   Legit  0.004969

 RandomForest1 Model
Acc: 0.9970714285714286
Matrix:
 [[13925     1]
 [   40    34]]

 Cases:
      Actual      Prob
2900   Legit  0.000146
3143   Legit  0.000214
8231   Legit  0.000596
3855   Legit  0.000197
8045   Legit  0.001549
7653   Legit  0.001120
8610   Legit  0.010103
7310   Legit  0.004269
10175  Legit  0.033114
5538   Legit  0.000386

 RandomForest2 Model
Acc: 0.9974285714285714
Matrix:
 [[13925     1]
 [   35    39]]

 Cases:
      Actual      Prob
2900   Legit  0.000011
3143   Legit  0.000085
8231   Legit  0.000002
3855   Legit  0.000113
8045   Legit  0.000354
7653   Legit  0.000444
8610   Legit  0.004542
7310   Legit  0.000